"use client";
import {useEffect,useState} from "react";
const projects=[{index:"01",name:"Rentalin",type:"SAAS / SYSTEM",text:"Billing, device control, and business operations for PS rental owners.",href:"https://rentalin.online"},{index:"02",name:"XL SATU",type:"WEB / COMMERCE",text:"A conversion-focused digital storefront for home internet sales.",href:"https://xlsatungebut.com"},{index:"03",name:"Kejar Target",type:"SAAS / GAMIFICATION",text:"Sales tracking, performance visibility, and team gamification.",href:"https://kejartarget.online"}];
function MotionFrame(){return <div className="motion-frame" aria-hidden="true"><div className="frame-grid"/><div className="frame-orbit orbit-one"/><div className="frame-orbit orbit-two"/><div className="frame-orbit orbit-three"/><div className="frame-core"><span/><span/><span/></div><div className="frame-line line-a"/><div className="frame-line line-b"/><div className="frame-line line-c"/><div className="frame-label label-a">AXL / 026</div><div className="frame-label label-b">SYSTEM / MOTION</div></div>}
export default function Home(){const[scrolled,setScrolled]=useState(false);const[pointer,setPointer]=useState({x:0,y:0});useEffect(()=>{const s=()=>setScrolled(scrollY>40);const m=(e:MouseEvent)=>setPointer({x:(e.clientX/innerWidth-.5)*2,y:(e.clientY/innerHeight-.5)*2});addEventListener("scroll",s,{passive:true});addEventListener("mousemove",m);return()=>{removeEventListener("scroll",s);removeEventListener("mousemove",m)}},[]);
return <main><nav className={scrolled?"nav nav-scrolled":"nav"}><a className="brand" href="#top">AXL<span>WORKS</span></a><div className="nav-links"><a href="#work">Work</a><a href="#lab">Lab</a><a href="#contact">Contact</a></div><a className="nav-status" href="https://github.com/AxellZoldyck/axlworks" target="_blank" rel="noreferrer"><i/> GitHub</a></nav>
<section id="top" className="hero"><div className="hero-noise"/><div className="hero-copy"><p className="eyebrow"><span/> DIGITAL SYSTEMS / 2026</p><h1>BUILDING<br/><em>DIGITAL</em><br/>SYSTEMS.</h1><p className="hero-description">Axlworks is a small software lab exploring products, interfaces, and the space between engineering and visual design.</p><div className="hero-actions"><a className="button button-dark" href="#work">Explore work <span>↘</span></a><a className="text-link" href="https://github.com/AxellZoldyck" target="_blank" rel="noreferrer">GitHub ↗</a></div></div><div className="hero-visual" style={{transform:`translate3d(${pointer.x*-10}px,${pointer.y*-8}px,0)`}}><MotionFrame/></div><div className="hero-meta"><span>01 — INTRO</span><span>SCROLL TO EXPLORE ↓</span></div></section>
<section id="work" className="section work-section"><div className="section-heading"><p className="eyebrow">SELECTED WORK</p><h2>Things that <em>ship.</em></h2></div><div className="project-list">{projects.map(p=><a className="project-row" href={p.href} target="_blank" rel="noreferrer" key={p.name}><span className="project-index">{p.index}</span><div className="project-main"><span className="project-type">{p.type}</span><h3>{p.name}</h3><p>{p.text}</p></div><span className="project-arrow">↗</span><div className="project-glow"/></a>)}</div></section>
<section id="lab" className="section lab-section"><div className="lab-visual"><div className="signal signal-one"/><div className="signal signal-two"/><div className="signal signal-three"/><div className="lab-center">LAB<br/><small>∞</small></div></div><div className="lab-copy"><p className="eyebrow">THE LAB</p><h2>Where ideas become <em>interfaces.</em></h2><p>Experiments live here: motion studies, generative visuals, product concepts, interaction patterns, and small tools that may eventually become real software.</p><div className="skill-line"><span>WEB</span><span>PRODUCT</span><span>UI / UX</span><span>SYSTEMS</span></div></div></section>
<section id="contact" className="contact-section"><div className="contact-orb"/><p className="eyebrow">START A CONVERSATION</p><h2>Have a system<br/>worth <em>building?</em></h2><a className="contact-link" href="mailto:hello@axlworks.co">hello@axlworks.co <span>↗</span></a></section><footer><div>AXLWORKS</div><div>DIGITAL SYSTEMS / EXPERIMENTS</div><div>© 2026</div></footer></main>}